### ISSUE TITLE
FRR and MPLS module

### ISSUE THREAD

**Issue by barajus** [ipspace/netlab-examples#23]
Hi back, I am still playing around with FRR and the cool kid (clab).

I was giving a try to https://github.com/ipspace/netlab-examples/tree/master/MPLS/vpn-simple and I found some issues with PE:

```
TASK [run /tmp/config.sh to deploy vrf config from /usr/local/lib/python3.10/dist-packages/netsim/ansible/tasks/../templates/vrf/frr.j2] *****************************************
fatal: [pe1]: FAILED! => changed=true
  cmd:
  - bash
  - /tmp/config.sh
  delta: '0:00:00.008140'
  end: '2024-03-13 21:58:35.758576'
  msg: non-zero return code
  rc: 2
  start: '2024-03-13 21:58:35.750436'
  stderr: 'Error: Unknown device type.'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
fatal: [pe2]: FAILED! => changed=true
  cmd:
  - bash
  - /tmp/config.sh
  delta: '0:00:00.006389'
  end: '2024-03-13 21:58:35.813947'
  msg: non-zero return code
  rc: 2
  start: '2024-03-13 21:58:35.807558'
  stderr: 'Error: Unknown device type.'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

(netlab version 1.7.0)

topology if needed:

```
provider: clab
defaults.device: frr

vrfs:
  red:
  blue:

bgp.as: 65000
mpls.ldp: True
mpls.vpn: True

nodes:
  pe1:
    module: [ vrf,ospf,bgp,mpls ]
  pe2:
    module: [ vrf,ospf,bgp,mpls ]
  h1:
    device: linux
  h2:
    device: linux
  h3:
    device: linux
  h4:
    device: linux

links:
- pe1: { vrf: red }
  h1:
- pe2: { vrf: red }
  h2:
- pe1: { vrf: blue }
  h3:
- pe2: { vrf: blue }
  h4:
- pe1-pe2
```
